import { firebaseService } from '../services/firebaseService';
import { Timestamp } from 'firebase/firestore';

export const useFinance = (selectedSeason, seasonalPlayers, isBudgetLocked) => {
  
  const calculatePlayerFinancials = (player, transactions = []) => {
    if (!transactions || !Array.isArray(transactions)) {
      return { baseFee: 0, totalPaid: 0, fundraising: 0, sponsorships: 0, credits: 0, remainingBalance: 0, isWaived: false };
    }

    const isCleared = (tx) => tx.cleared === true || String(tx.cleared).toLowerCase() === 'true';
    const seasonTxs = transactions.filter(tx => tx.seasonId === selectedSeason && isCleared(tx));
    
    const fullName = `${player.firstName} ${player.lastName}`.trim().toLowerCase();

    const playerTxs = seasonTxs.filter(tx => {
      if (tx.playerId === player.id) return true;
      const txName = (tx.playerName || tx.Name || '').trim().toLowerCase();
      return txName === fullName;
    });

    const isWaived = player.seasonProfiles?.[selectedSeason]?.feeWaived || false;
    const baseFee = isWaived ? 0 : Number(player.seasonProfiles?.[selectedSeason]?.baseFee ?? 750);

    let paid = 0, fun = 0, spo = 0, cre = 0;
    
    playerTxs.forEach(tx => {
      const amt = Number(tx.amount || 0);
      
      if (tx.category === 'TMF') paid += amt;
      if (tx.category === 'FUN') fun += amt;
      
      // FIX: Only apply SPO if it was generated by the Waterfall distribution. Raw ledger SPOs are ignored.
      if (tx.category === 'SPO' && tx.waterfallBatchId) spo += amt; 
      
      if (tx.category === 'CRE') cre += amt;
    });

    const remainingBalance = Math.max(0, baseFee - (paid + fun + spo + cre));

    return { baseFee, totalPaid: paid, fundraising: fun, sponsorships: spo, credits: cre, remainingBalance, isWaived };
  };

  const handleWaterfallCredit = async (totalAmount, title, sourcePlayerId, originalTxId) => {
    if (!isBudgetLocked) throw new Error("Budget must be finalized first.");

    const batchId = `waterfall_${Date.now()}`;
    const amount = parseFloat(totalAmount);

    if (sourcePlayerId) {
      const player = seasonalPlayers.find(p => p.id === sourcePlayerId);
      
      await firebaseService.addDocument('transactions', {
        title: `${title} (Credit)`,
        amount: amount,
        playerId: sourcePlayerId,
        playerName: `${player.firstName} ${player.lastName}`,
        category: 'SPO',
        seasonId: selectedSeason,
        waterfallBatchId: batchId,
        originalTxId: originalTxId || null,
        date: Timestamp.now(),
        cleared: true
      });
      
      if (originalTxId) {
        await firebaseService.updateDocument('transactions', originalTxId, { distributed: true });
      }
    }
    return batchId;
  };

  const revertWaterfall = async (batchId, originalTxId) => {
    await firebaseService.deleteBatch('transactions', 'waterfallBatchId', batchId);
    
    if (originalTxId) {
      await firebaseService.updateDocument('transactions', originalTxId, { distributed: false });
    }
  };

  return { calculatePlayerFinancials, handleWaterfallCredit, revertWaterfall };
};