import { firebaseService } from '../services/firebaseService';
import { Timestamp } from 'firebase/firestore';

export const useLedgerManager = (refreshData, selectedSeason, handleWaterfallCredit) => {
  const handleSaveTransaction = async (txData) => {
    try {
      // Ensure date is properly converted to a Firestore Timestamp
      const formattedData = {
        ...txData,
        date: typeof txData.date === 'string' ? Timestamp.fromDate(new Date(`${txData.date}T12:00:00`)) : txData.date
      };

      if (formattedData.id) {
        await firebaseService.updateDocument('transactions', formattedData.id, formattedData);
      } else {
        // AUTOMATED WATERFALL: If category is Fundraising (FUN), trigger waterfall immediately
        if (formattedData.category === 'FUN' && formattedData.playerId) {
          await handleWaterfallCredit(formattedData.amount, formattedData.title, formattedData.playerId);
        } else {
          await firebaseService.addDocument('transactions', { ...formattedData, seasonId: selectedSeason });
        }
      }
      await refreshData();
      return { success: true };
    } catch (error) {
      console.error("Transaction save failed:", error);
      return { success: false, error: error.message };
    }
  };

  const handleDeleteTransaction = async (txId) => {
    try {
      // 1. Delete the primary transaction (The Sponsor Deposit)
      await firebaseService.deleteDocument('transactions', txId);
      
      // 2. Cascading Delete: Find and wipe any waterfall distributions 
      // (player credits or team pool overflows) that were generated by this transaction
      await firebaseService.deleteBatch('transactions', 'originalTxId', txId);
      
      // 3. Refresh the UI data
      await refreshData();
      return { success: true };
    } catch (error) {
      console.error("Failed to delete transaction and its distributions:", error);
      throw error;
    }
  };

  return { handleSaveTransaction, handleDeleteTransaction };
};